### ISSUE TITLE
[PE-D] The UG is not organized well in terms of content flow.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2113T-T12-3/tp#182] opened 2021-10-30 18:25 UTC
The UG on the command should be separated to the following as an example. 

- ADD commands
- LIST/VIEW commands 
- EDIT commands
- FIND commands
- DELETE commands
- STATS commands like "balance" 

For now the UG command is quite messy as I have to move up and down just to find a particular command. 

It is better for you to streamline a demo process thinking about what to do as a starter guide for a newbie user. 

-------------
Labels: `type.DocumentationBug` `severity.High`
original: YEOWEIHNGWHYELAB/ped#8

**Comment by AnShengLee** [comment] 2021-11-01 16:43
Duplicate of #175

**Comment by KZQ1999** [comment] 2021-11-01 17:22
Take a look at the new UG, leave some comments here @jonathanlkw  @Nirmaleshwar  @kyun99 
if not this should be okay :D

**Closed** 2021-11-06 17:23 UTC
Labels: DUPLICATE
